// generated by Fast Light User Interface Designer (fluid) version 1.0300

#ifndef liquids_h
#define liquids_h
#include <FL/Fl.H>
#include <iostream>
#include <FL/Fl_Double_Window.H>
extern Fl_Double_Window *setupWin;
#include <FL/Fl_Tabs.H>
extern Fl_Tabs *tabSetup;
#include <FL/Fl_Group.H>
extern Fl_Group *tabParams;
#include <FL/Fl_Value_Input.H>
extern Fl_Value_Input *valueLx;
extern Fl_Value_Input *valueLy;
extern Fl_Value_Input *valueLz;
extern Fl_Value_Input *valueDeltaT;
extern Fl_Value_Input *valueDensity;
extern Fl_Value_Input *valueTotalTime;
extern Fl_Value_Input *valueTemperature;
extern Fl_Group *tabDynamics;
#include <FL/Fl_Choice.H>
extern Fl_Choice *choiceDynamics;
extern Fl_Value_Input *valueRcCutoff;
extern Fl_Value_Input *valueRlCutoff;
extern Fl_Value_Input *valueDampingConstant;
extern Fl_Value_Input *valueVelRelaxationTime;
extern Fl_Value_Input *valueMCStepSize;
extern Fl_Value_Input *valueMCStepSizeTheta;
#include <FL/Fl_Check_Button.H>
extern Fl_Check_Button *checkDoMCStepRescale;
extern Fl_Value_Input *valueXYJ;
extern Fl_Group *tabInitPos;
extern Fl_Choice *initPosChoice;
extern Fl_Choice *initVelChoice;
extern Fl_Value_Input *valueThresholdInitRandPos;
extern Fl_Value_Input *valueTwoPartVel;
extern Fl_Group *tabProteins;
extern Fl_Check_Button *checkPutPolymers;
extern Fl_Value_Input *valueNumChains;
extern Fl_Value_Input *valueNumAtomsPerChain;
extern Fl_Value_Input *valueBondLength;
extern Fl_Group *tabMinimize;
extern Fl_Check_Button *checkSteepDescMinim;
extern Fl_Group *tabMeasures;
extern Fl_Check_Button *checkDoVacf;
extern Fl_Check_Button *checkDoPcf;
extern Fl_Check_Button *checkDoR;
extern Fl_Value_Input *valueTimeMeasure;
extern Fl_Value_Input *valueNHisPcf;
#include <FL/Fl_Return_Button.H>
extern Fl_Return_Button *applyParamBut;
extern Fl_Double_Window *toolsWin;
extern Fl_Tabs *tabTools;
extern Fl_Group *tabRunParams;
#include <FL/Fl_Value_Output.H>
extern Fl_Value_Output *valueOutputReqTemp;
extern Fl_Value_Output *valueOutputTemp;
#include <FL/Fl_Repeat_Button.H>
extern Fl_Repeat_Button *butScaleTemp;
extern Fl_Group *tabParticles;
extern Fl_Value_Input *valueTagParticle;
extern Fl_Value_Output *valueTotNumParticles;
extern Fl_Check_Button *checkTagPart;
#include <FL/Fl_Button.H>
extern Fl_Button *butTagPart;
#include "gl_obj.h"
extern Fl_Double_Window *mainWin;
#include <FL/Fl_Box.H>
extern gl_obj *mainBox;
#include <FL/Fl_Menu_Bar.H>
extern Fl_Return_Button *stepButton;
extern Fl_Return_Button *runButton;
extern Fl_Value_Output *simuTime;
#include <FL/Fl_Spinner.H>
extern Fl_Spinner *freq_anim;
extern Fl_Menu_Item menu_choiceDynamics[];
#define choiceDynLJN2 (menu_choiceDynamics+0)
#define choiceDynLJRc (menu_choiceDynamics+1)
#define choiceDynLJRcVerletLists (menu_choiceDynamics+2)
#define choiceDynHardSpheres (menu_choiceDynamics+3)
#define choiceDynLangevin (menu_choiceDynamics+4)
#define choiceDynLangevin2 (menu_choiceDynamics+5)
#define choiceDynMCLJ (menu_choiceDynamics+6)
#define choiceDynMCLJXY (menu_choiceDynamics+7)
#define choiceDynMCLJLL (menu_choiceDynamics+8)
#define choiceDynMCLJNPT (menu_choiceDynamics+9)
#define choiceDynLJN2Polymers (menu_choiceDynamics+10)
#define choiceDynLJRcVerletListsPolymers (menu_choiceDynamics+11)
extern Fl_Menu_Item menu_initPosChoice[];
extern Fl_Menu_Item menu_initVelChoice[];
extern Fl_Menu_Item menu_[];
#define setupParamsMenu (menu_+6)
#define writeVelsMenu (menu_+7)
#define toolsDialog (menu_+15)
void calc(void);
void anim(void*);
void showParamsWindow(void);
void applyParamsButton(void);
void applyParams(void);
void Inits(void);
void showToolsWindow(void);
void applyCheckTagParticle(void);
void applyRescaleVels(void);
void choiceDynamicsHideButtons(void);
void WritePositions(int);
void ReadPositions(void);
void saveAllVels(void);
void writeTagTrajectory(void);
void Pause(void);
void Step(void);
void Run(void);
void ExitFunc(void);
#endif
